# Generated by Django 4.2.1 on 2023-05-18 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_employees'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drinks',
            new_name='Drink',
        ),
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
